name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - name: Install Garden
        run: cargo install garden-tools
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: |
          set -x
          sudo apt-get update
          # Runtime dependencies (required)
          sudo apt-get install shellcheck
      - name: Run tests and checks
        run: garden -vv check
